# Site settings
title: Mauna Masszázs Stúdió 1
description: ""
baseurl: "http://ylonil.github.io/mauna" # the subpath of your site, e.g. /blog
url: "http://ylonil.github.io/mauna" # the name of your domain
logo_url: svg/min/logo.svg

# Hero
hero: 
    hero_img: hero.jpg
    hero_title: Mauna Masszázs Stúdió
    hero_description: Szeretettel várunk minden kedves vendéget.

# Contact form
api_token: # Enter API token here

# Contact info
contact:
    phone: +36 70 624 0064
    address: Rácvárosi út 16. <br> Pécs

# Opening hours
monday_friday: TBA
saturday: TBA
sunday: TBA

# Testimonials
testimonials:
    testimonials_img: parallax.jpg

# Map
map:
    zoom: 17
    address: Pécs, Rácvárosi út 16.
    address_details: svg/min/logo.svg

# Social settings
facebook: https://www.facebook.com/maunamasszazs.pecs
feed: yes

# Footer
copyright: 2016 Mauna Masszás Stúdió

# Build settings
markdown: kramdown

sass:
    sass_dir: _scss

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore
]

# Theme Settings
analytics: 
google_verification:
